version: 2

updates:
  # ==============
  # KOTLIN BACKEND
  # ==============
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    open-pull-requests-limit: 10
    groups:
      quarkus:
        patterns:
          - "io.quarkus*"
          - "io.quarkiverse*"
      backend:
        patterns:
          - "org.apache.maven*"
          - "io.mockk*"

  # ==============
  # Docker backend
  # ==============
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
    groups:
      docker-frontend:
        patterns:
          - "*"